### ISSUE TITLE
Commitment Cost Estimation Chooses Commitment over Replication in this program

### ISSUE THREAD

**Issue by ianwilkietomasik** [apl-cornell/viaduct#270] opened 2021-11-05 15:40 UTC
```
host alice : {A}
host bob   : {B}
host chuck : {C}
host dave  : {D}

process main {
  var x: int{C ⊓ D} = 5;

  val y: int{(A | B | C)-> & (C & D)<-} = declassify x to {(A | B | C)-> & (C & D)<-};
  val z: int{(A | B | C)-> & (C & D & A)<-} = endorse y from {(A | B | C)-> & (C & D)<-};
  }
```

**Comment by ianwilkietomasik** [comment] 2021-11-08 17:22
ZKP chosen over commitments in this example
```
host alice : {A}
host bob   : {B}
host chuck : {C}

process main {
  val x: int {C} = input int from chuck;

  val y: int{(A | B | C)-> & (C)<-} = declassify x to {(A | B | C)-> & (C)<-};
  val z: int{(A | B | C)-> & (C & A & B)<-} = endorse y from {(A | B | C)-> & (C)<-};
  output z to alice;
  output z to bob;
}
```

**Comment by rolph-recto** [comment] 2021-11-08 19:05
This is a cost estimator issue. For the second example, when ZKP execution cost is 20 and replication cost is 1, `z` is assigned to ZKP. Increasing ZKP exec cost to 50 makes `z` assigned to replication as intended.

**Comment by rolph-recto** [comment] 2021-11-09 05:43
I thought about this some more and the first one is not a bug either. `y` and `z` must have the trust of Dave but Dave cannot read them because they have confidentiality `(A | B | C)->`. That means Dave needs to be sent a commitment!

If instead Dave can read `y` and `z`, as in the following example, we get the compilation we expect:
```
host alice : {A}
host bob : {B}
host chuck : {C}
host dave : {D}

fun main() {
    var x: int{(C ⊓ D)}@Replication(hosts = {chuck, dave}) = 5;
    let $tmp@Replication(hosts = {chuck, dave}) = x;
    let $tmp_1@Replication(hosts = {chuck, dave}) = declassify $tmp to {(((A | C) | D)-> & (C & D)<-)};
    val y: int{(((A | C) | D)-> & (C & D)<-)}@Replication(hosts = {chuck, dave}) = $tmp_1;
    let $tmp_2@Replication(hosts = {chuck, dave}) = y;
    let $tmp_3@Replication(hosts = {alice, chuck, dave}) = endorse $tmp_2 from {(((A | C) | D)-> & (C & D)<-)};
    val z: int{(((A | C) | D)-> & ((C & D) & A)<-)}@Replication(hosts = {alice, chuck, dave}) = $tmp_3;
}
```

We have explanations for both buggy compilations (they're not bugs at all, it turns out), so I'm closing this issue.

**Closed by rolph-recto** 2021-11-09 05:43 UTC
